<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Client Logos', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-PXnwUr","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50","bottom":"50","right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"20","left":"10"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":26,"Mobile":null},"elementId":"guten-G1MRmF","verticalAlign":{"Desktop":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"padding":{"Mobile":[]}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-pkxPSr","alignText":{"Mobile":"center"},"titleTag":"h3","text":"Trusted by ","focusText":"500+ Companies","subText":"","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"primary"},"mainTypography":{"type":"variable","id":"h3-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"type":"variable","id":"primary"},"focusTypography":{"type":"variable","id":"h3-bold-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"20"}},"Desktop":[]},"padding":{"Tablet":[],"Mobile":[],"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":74,"Tablet":null},"elementId":"guten-FeY7Qm","verticalAlign":{"Desktop":"center","Tablet":"center"},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/logo-slider {"elementId":"guten-tHeFaV","logos":[{"title":"One","_key":"bpyY5w","src":{"id":658,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/financio-client-logo-neww.webp","width":300,"height":86,"altOriginal":"financio client logo"},"imageLoad":"lazy"},{"title":"Two","_key":"94trKw","src":{"id":659,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/renovater-client-logo-neww.webp","width":300,"height":86,"altOriginal":"renovater client logo"},"imageLoad":"lazy"},{"title":"Three","_key":"hYIa1Z","src":{"id":660,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/intrace-client-logo-neww.webp","width":300,"height":86,"altOriginal":"intrace client logo"},"imageLoad":"lazy"},{"title":"Four","_key":"POuiik","src":{"id":661,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/startupzy-logo-client-new.webp","width":300,"height":86,"altOriginal":"startupzy logo client"},"imageLoad":"lazy"}],"imagePadding":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}},"Tablet":{"unit":"px","dimension":{"left":"30","top":"0","right":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"imageMargin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"imageHoverPadding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"imageHoverMargin":{"Tablet":[],"Mobile":[]},"imageBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"imageBorderHover":{"radius":{"Tablet":[],"Mobile":[]}},"spacing":{"Desktop":"30","Tablet":"0","Mobile":"20"},"itemShowed":{"Desktop":"4","Tablet":"3","Mobile":"2"},"loop":true,"dotsRadius":{"Tablet":[],"Desktop":[]},"arrowPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"arrowMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"arrowOpacity":{"Desktop":""},"arrowBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"opacity":"0.7","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"10","left":"10"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
