<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Single Post Hero', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"700"},"gap":"no","elementId":"guten-EjVPp5","background":{"type":"default","color":{"type":"variable","id":"fourteenth"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":1128,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/BG-Blur.webp"}},"position":{"Desktop":"bottom center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"xposition":{"Desktop":{"point":"","unit":"px"}},"yposition":{"Desktop":{"point":"","unit":"px"}}},"opacity":"1","border":{"radius":{"Desktop":[]}},"bottomDivider":{"type":"tilt_g","flip":false,"colorMode":"gradient","color":{"r":255,"g":255,"b":255,"a":1},"height":{"Desktop":"300","Tablet":"200","Mobile":"150"},"width":{"Desktop":"100"},"gradientColor":[{"color":"rgba(56, 79, 102, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(59, 40, 101, 1)","active":true,"opacity":1,"id":5,"offset":"1.000"}],"gradientAngle":"0","gradientColor3":[{"color":"rgba(47, 108, 252, 1)","opacity":1,"active":false,"id":2,"offset":"0.000"},{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"}],"gradientColor2":[{"color":"rgba(185, 92, 242, 0.2)","active":true,"opacity":0.2,"id":13,"offset":"0.000"},{"color":"rgba(47, 108, 252, 0.2)","active":false,"opacity":0.2,"id":5,"offset":"1.000"}],"gradientAngle2":"0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"140","bottom":"320","right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"120","right":"20","bottom":"220","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"100","right":"10","bottom":"180","left":"10"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-YytRR3","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"slow"}} -->
<!-- wp:gutenverse/post-title {"elementId":"guten-I2o5ru","htmlTag":"h2","alignment":{"Desktop":"center"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"color":{"type":"variable","id":"white"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"}} -->
<div class="guten-element guten-post-title guten-I2o5ru animated guten-element-hide desktop-fadeInDown"></div>
<!-- /wp:gutenverse/post-title -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-4aYKi2","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-C1ogVY","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Mobile":[]},"padding":{"Mobile":[]}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-L2kNKU","icon":"fas fa-user-circle","iconColorOne":{"r":47,"g":108,"b":252,"a":0},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-accent"},"background":{"type":"default","color":""},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","bottom":"-5"}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10","top":"10"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-author {"elementId":"guten-AB1YQy","postId":"1","backendPostId":"1","typography":{"type":"variable","id":"gv-font-text","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"color":{"type":"variable","id":"fifth"},"authorBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"40","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"20","top":"10"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-author guten-AB1YQy"></div>
<!-- /wp:gutenverse/post-author -->

<!-- wp:gutenverse/icon {"elementId":"guten-OR1uoJ","icon":"fas fa-calendar-alt","iconColorOne":{"r":47,"g":108,"b":252,"a":0},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-accent"},"background":{"type":"default","color":""},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","bottom":"-5"}},"Mobile":{"unit":"px","dimension":{"right":"10","top":"10","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-date {"elementId":"guten-cmBGxO","postId":"1","backendPostId":"1","noContentText":"","htmlTag":"p","typography":{"type":"variable","id":"gv-font-text","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"color":{"type":"variable","id":"fifth"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"0","bottom":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"right":"20","bottom":"-3","top":"10"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":""}},"Tablet":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-date guten-cmBGxO"></div>
<!-- /wp:gutenverse/post-date -->

<!-- wp:gutenverse/icon {"elementId":"guten-JMwXVv","icon":"fas fa-folder-open","iconColorOne":{"r":47,"g":108,"b":252,"a":0},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-accent"},"background":{"type":"default","color":""},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","bottom":"-5"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"","left":""}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-terms {"elementId":"guten-AgLoQa","postId":"1","backendPostId":"1","typography":{"type":"variable","id":"gv-font-text","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"color":{"type":"variable","id":"fifth"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"","left":""}}},"padding":{"Mobile":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-terms guten-AgLoQa"></div>
<!-- /wp:gutenverse/post-terms -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
