<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home CTA', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-ZKFSzf","background":{"type":"default","image":{"Desktop":{"id":1148,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/app-application-business-business-strategy-coffee-collaboration-1434201-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"gradientColor":[{"color":"rgba(185, 92, 242, 0.45)","opacity":0.45,"active":true,"id":1,"offset":"0.000"},{"color":"rgb(126, 32, 207)","active":false,"id":2,"offset":"1.000"}]},"backgroundOverlay":{"type":"gradient","color":{"r":1,"g":1,"b":29,"a":1},"gradientColor":[{"color":"rgba(90, 26, 129, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(11, 30, 76, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":230},"opacity":"0.9","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"20","bottom":"100","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"20","bottom":"80","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"60","right":"20","bottom":"60","left":"20"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-iVeeM9","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":""}}}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-hrRPB9","alignText":{"Desktop":"flex-start","Tablet":"center"},"subTag":"h2","text":"Have a Project On Your Mind? Let’s ","focusText":"Work Together","subText":"","showSub":"top","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"white"},"mainTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"type":"variable","id":"white"},"focusTypography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"focusBackground":{"type":"gradient","gradientColor":[{"color":"rgba(49, 207, 180, 0)","active":false,"opacity":0,"id":1,"offset":"0.555"},{"color":"rgba(212, 120, 252, 1)","opacity":1,"active":false,"id":2,"offset":"0.557"},{"color":"rgba(185, 92, 242, 1)","active":true,"opacity":1,"id":3,"offset":"1.000"}]},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"subPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[],"Tablet":[]},"animation":{"type":{"Desktop":"fadeInLeft"}}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-CrkGaU","gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"left","Tablet":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"text-font","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"40","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit aenean.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-2spiVS","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<!-- wp:gutenverse/button {"elementId":"guten-9ObbbO","content":"Contact Us","url":"#","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"white"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"thirteenth"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none","width":"","color":{"r":255,"g":255,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"gtn gtn-long-arrow-alt-right-solid","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yMS4xODggOS4yODFsLTEuNDA2IDEuNDM4IDQuMjgxIDQuMjgxaC0yMC4wNjN2MmgyMC4wNjNsLTQuMjgxIDQuMjgxIDEuNDA2IDEuNDM4IDYuNzE5LTYuNzE5eiI+PC9wYXRoPgo8L3N2Zz4K","iconPosition":"after","iconSpacing":{"Desktop":"25"},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"background":{"type":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"all":{"type":"none"}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none"},"right":{"type":"none"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"},"color":{"type":"variable","id":"secondary"},"iconColor":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverIconColor":{"type":"variable","id":"white"},"hoverTextColor":{"type":"variable","id":"white"},"positioningType":{"Desktop":"inline"},"ariaLabel":"contact us"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
