<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Archive Hero', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"700"},"gap":"no","elementId":"guten-EjVPp5","background":{"type":"default","color":{"type":"variable","id":"fourteenth"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":1128,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/BG-Blur.webp"}},"position":{"Desktop":"bottom center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"xposition":{"Desktop":{"point":"","unit":"px"}},"yposition":{"Desktop":{"point":"","unit":"px"}}},"opacity":"1","border":{"radius":{"Desktop":[]}},"bottomDivider":{"type":"tilt_g","flip":false,"colorMode":"gradient","color":{"r":255,"g":255,"b":255,"a":1},"height":{"Desktop":"300","Tablet":"200","Mobile":"150"},"width":{"Desktop":"100"},"gradientColor":[{"color":"rgba(56, 79, 102, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(59, 40, 101, 1)","active":true,"opacity":1,"id":5,"offset":"1.000"}],"gradientAngle":"0","gradientColor3":[{"color":"rgba(47, 108, 252, 1)","opacity":1,"active":false,"id":2,"offset":"0.000"},{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"}],"gradientColor2":[{"color":"rgba(185, 92, 242, 0.2)","active":true,"opacity":0.2,"id":13,"offset":"0.000"},{"color":"rgba(47, 108, 252, 0.2)","active":false,"opacity":0.2,"id":5,"offset":"1.000"}],"gradientAngle2":"0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"140","bottom":"320","right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"120","right":"20","bottom":"220","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"100","right":"","bottom":"180","left":""}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-YytRR3","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"}} -->
<!-- wp:gutenverse/archive-title {"elementId":"guten-x9Fy4H","alignment":{"Desktop":"center"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"color":{"type":"variable","id":"fifteenth"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
