<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse 404 Hero', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1140"},"gap":"no","elementId":"guten-EjVPp5","heightControl":"fit","background":{"type":"default","color":{"type":"variable","id":"fourteenth"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":1144,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/BG-gaussian-blur-3.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"opacity":"1","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"-59","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"160","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"20","bottom":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"20","bottom":"","left":"20"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"elementId":"guten-YytRR3","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-l32Ewe","alignText":{"Desktop":"center"},"titleTag":"h1","subTag":"h3","text":"","focusText":"404","subText":"Page Not Found","showLine":"none","lineMargin":{"Desktop":[]},"mainMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"focusColor":{"type":"variable","id":"white"},"focusTypography":{"type":"variable","id":"gv-font-heading-404","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"150"},"Tablet":{"unit":"px","point":"140"},"Mobile":{"unit":"px","point":"120"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"700"},"focusBackground":{"type":"gradient","gradientColor":[{"color":"rgba(126, 32, 207, 0)","active":false,"opacity":0,"id":2,"offset":"0.594"},{"color":"rgba(207, 130, 251, 1)","opacity":1,"active":false,"id":1,"offset":"0.594"},{"color":"rgba(196, 113, 247, 1)","active":true,"opacity":1,"id":3,"offset":"1.000"}]},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":[],"Tablet":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subColor":{"type":"variable","id":"white"},"subTypography":{"type":"variable","id":"funfact-number-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"},"Mobile":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"700"},"subMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"subPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"0","right":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-JXaDGD","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","right":"","left":"","top":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}},"Mobile":[]}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit aenean commodo.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/search {"elementId":"guten-L8jfKL","formStyle":{"Desktop":"fit-content","Mobile":"100%"},"buttonWidth":{"Desktop":{"point":"10","unit":"%"},"Tablet":{"unit":"%","point":"20"},"Mobile":{"unit":"%","point":"100"}},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputPlaceholder":"Search","inputPadding":{"Desktop":{"unit":"px","dimension":{"left":"30","right":"30","top":"15","bottom":"15"}},"Mobile":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"15"}}},"inputHeight":{"Desktop":"55","Tablet":""},"inputWidth":{"Desktop":{"unit":"%","point":"68"},"Tablet":{"unit":"%","point":"80"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400","transform":"normal","decoration":"none","style":"normal"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-text-secondary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"10"}}},"all":{"type":"none","width":null,"color":""},"top":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-border"}},"left":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-border"}},"bottom":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-border"}},"right":{"type":"none"}},"inputBorderNormalResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-border"}}}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-accent"}}},"inputBorderHoverResponsive":{"Mobile":{"radius":[],"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-accent"}}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-accent"}}},"inputBorderFocusResponsive":{"Mobile":{"radius":[],"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-accent"}}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"gv-color-white"}},"alignContent":{"Desktop":"center"}} -->
<!-- wp:gutenverse/button {"elementId":"guten-hxUxS1","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Mobile":"100","Desktop":"100"},"buttonHeight":{"Mobile":"50"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"right":"30","left":"30","top":"15","bottom":"15"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"buttonBackground":{"color":{"type":"variable","id":"gv-color-accent"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"10","left":"0"}}}},"buttonBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500","transform":"normal","decoration":"none","style":"normal"}} /-->
<!-- /wp:gutenverse/search -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
