<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'vorfolio' ),
	'categories' => array( 'vorfolio-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-EjVPp5","background":{"type":"default","color":{"type":"variable","id":"fourteenth"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":1128,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/BG-Blur.webp"}},"position":{"Desktop":"bottom center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"xposition":{"Desktop":{"point":"","unit":"px"}},"yposition":{"Desktop":{"point":"","unit":"px"}}},"opacity":"1","border":{"radius":{"Desktop":[]}},"bottomDivider":{"type":"tilt_g","flip":false,"colorMode":"gradient","color":{"r":255,"g":255,"b":255,"a":1},"height":{"Desktop":"300","Tablet":"200","Mobile":"150"},"width":{"Desktop":"100"},"gradientColor":[{"color":"rgba(56, 79, 102, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(59, 40, 101, 1)","active":true,"opacity":1,"id":5,"offset":"1.000"}],"gradientAngle":"0","gradientColor3":[{"color":"rgba(47, 108, 252, 1)","opacity":1,"active":false,"id":2,"offset":"0.000"},{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"}],"gradientColor2":[{"color":"rgba(185, 92, 242, 0.2)","active":true,"opacity":0.2,"id":13,"offset":"0.000"},{"color":"rgba(47, 108, 252, 0.2)","active":false,"opacity":0.2,"id":5,"offset":"1.000"}],"gradientAngle2":"0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"140","bottom":"390","right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"160","right":"20","bottom":"380","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"180","right":"","bottom":"360","left":""}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":57.19,"Tablet":100},"elementId":"guten-YytRR3","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"80","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"150"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-l32Ewe","titleTag":"h1","text":"Hi, My Name Alice ","focusText":"I’m Professional","subText":"","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"white"},"mainTypography":{"type":"variable","id":"gv-font-primary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"46"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":[]},"focusColor":{"type":"variable","id":"white"},"focusTypography":{"type":"variable","id":"gv-font-primary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"focusBackground":{"type":"gradient","gradientColor":[{"color":"rgba(126, 32, 207, 0)","active":false,"opacity":0,"id":2,"offset":"0.594"},{"color":"rgba(207, 130, 251, 1)","opacity":1,"active":false,"id":1,"offset":"0.594"},{"color":"rgba(196, 113, 247, 1)","active":true,"opacity":1,"id":3,"offset":"1.000"}]},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subMargin":{"Desktop":[],"Tablet":[]},"subPadding":{"Desktop":[],"Tablet":[]},"border":{"radius":{"Desktop":[]}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-v8uSDv","content":"Web Designer","color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-primary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"60"},"Mobile":{"unit":"px","point":"46"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Tablet":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":42.81,"Tablet":72.26,"Mobile":null},"elementId":"guten-iibZe6","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}}} -->
<!-- wp:gutenverse/popup-builder {"elementId":"guten-iufYe3","width":{"Desktop":{"point":"820","unit":"px"},"Tablet":{"point":"740","unit":"px"},"Mobile":{"unit":"px","point":"320"}},"maxHeight":{"Desktop":{"unit":"vh"}},"containerPadding":{"Desktop":[]},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"backgroundColor":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"20"},"hideMobile":true,"overlayColor":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0.77}},"closeIconType":"svg","closeIconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik04IDI0LjY2N2MtMC4xNzEgMC0wLjM0MS0wLjA2NS0wLjQ3MS0wLjE5Ni0wLjI2LTAuMjYtMC4yNi0wLjY4MyAwLTAuOTQzbDE2LTE2YzAuMjYtMC4yNiAwLjY4My0wLjI2IDAuOTQzIDBzMC4yNiAwLjY4MyAwIDAuOTQzbC0xNiAxNmMtMC4xMzEgMC4xMzEtMC4zMDEgMC4xOTYtMC40NzIgMC4xOTZ6TTI0IDI0LjY2N2MtMC4xNzEgMC0wLjM0MS0wLjA2NS0wLjQ3MS0wLjE5NmwtMTYtMTZjLTAuMjYtMC4yNi0wLjI2LTAuNjgzIDAtMC45NDNzMC42ODMtMC4yNiAwLjk0MyAwbDE2IDE2YzAuMjYgMC4yNiAwLjI2IDAuNjgzIDAgMC45NDMtMC4xMzEgMC4xMzEtMC4zMDEgMC4xOTYtMC40NzIgMC4xOTZ6Ij48L3BhdGg+Cjwvc3ZnPgo=","closeButtonColor":{"Desktop":{"type":"variable","id":"white"},"Mobile":{"type":"variable","id":"gv-color-text-primary"}},"closeButtonBgColor":{"type":"default","color":{"type":"variable","id":"twelfth"}},"closeButtonSize":{"Desktop":"18","Mobile":"16"},"closePositioningLeft":{"Desktop":{"point":"776","unit":"px"},"Tablet":{"point":"696","unit":"px"},"Mobile":{"point":"282","unit":"px"}},"closePositioningRight":{"Desktop":{"point":"20","unit":"px"}},"closePositioningTop":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"closePositioningBottom":{"Desktop":{"unit":"px"}},"closePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"closeBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[],"Mobile":[]}},"closeBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[],"Mobile":[]}}} -->
<!-- wp:gutenverse/popup-container {"elementId":"guten-WPiHNb","position":"above"} -->
<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-wEGS1e","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Mobile":[],"Desktop":[]},"padding":{"Mobile":[],"Desktop":[]},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":70,"Tablet":null,"Mobile":null},"elementId":"guten-VJnpE3","background":{"type":"default","color":{"type":"variable","id":"white"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"right":"","bottom":"","left":"20","top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[]}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","right":"50","bottom":"80","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"40","left":"20"}}}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-hVJ4AC","alignText":{"Desktop":"center"},"subTag":"h4","text":"Join Our ","focusText":"Newsletter","subText":"","showSub":"top","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"mainPadding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"38"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"focusBackground":{"type":"gradient","gradientColor":[{"color":"rgba(49, 207, 180, 0)","active":false,"opacity":0,"id":1,"offset":"0.541"},{"color":"rgba(234, 186, 255, 1)","opacity":1,"active":true,"id":2,"offset":"0.543"}]},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":[],"Tablet":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-k5SKVW","columns":{"Desktop":"1","Tablet":""},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"3","left":"3","top":"","bottom":""}}}} -->
<!-- wp:paragraph -->
<p>Be the first to get exclusive offers and the latest design, projects and news directly to your inbox.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/form-input-email {"elementId":"guten-FVdYdy","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"helperPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"5","left":"5","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPlaceholder":"youremail@domain.com","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"13","bottom":"15","right":"20","left":"30"}},"Tablet":[],"Mobile":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","right":"","left":""}},"Tablet":[],"Mobile":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputTypography":{"type":"variable","id":"title-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":[],"Mobile":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-text-placeholder"}}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-accent"}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-accent"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} /-->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-L8NRF2","content":"Subscribe Now","buttonWidth":{"Desktop":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"5","left":"5"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-button-primary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}},"Mobile":[]}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":30,"Mobile":null},"elementId":"guten-P1amJK","background":{"type":"default","image":{"Desktop":{"id":19,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_E5GUBD8MWN.webp"}},"position":{"Desktop":"custom"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"xposition":{"Desktop":{"point":"-70","unit":"px"}},"yposition":{"Desktop":{"point":"","unit":"px"}}},"opacity":"0.7","verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"20","left":"","right":"20"}}}},"hideMobile":true} /-->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/popup-container -->
<!-- /wp:gutenverse/popup-builder -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-mxFyIR","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"fifth"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"24"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"200"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa cum sociis natoque penatibus et magnis dis parturient montes.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-HVU6v1","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"400"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":31,"Tablet":28,"Mobile":50},"sectionVerticalAlign":"center","elementId":"guten-L76qez","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10"}},"Tablet":[]}} -->
<!-- wp:gutenverse/image {"elementId":"guten-vD3ykf","imgSrc":{"media":{"imageId":813,"sizes":{"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/man-tree-plant-street-house-flower.webp","height":107,"width":80,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"man tree plant street","captionOriginal":"","width":{"Desktop":{"point":"40","unit":"px"}},"height":{"Desktop":{"unit":"px","point":"40"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"},"imageLoad":"eager","fetchPriorityHigh":true,"className":"wp-block-gutenverse-image guten-element guten-image guten-vD3ykf"} /-->

<!-- wp:gutenverse/image {"elementId":"guten-KmNSfq","imgSrc":{"media":{"imageId":814,"sizes":{"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/pretty-girl-in-white.webp","height":80,"width":80,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"pretty girl in white","captionOriginal":"","width":{"Desktop":{"point":"40","unit":"px"}},"height":{"Desktop":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-10"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"imageLoad":"eager","fetchPriorityHigh":true,"className":"wp-block-gutenverse-image guten-element guten-image guten-KmNSfq"} /-->

<!-- wp:gutenverse/image {"elementId":"guten-U0mp05","imgSrc":{"media":{"imageId":815,"sizes":{"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/ambitious-attractive-boss-business-businessman-challenge.webp","height":80,"width":80,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"attractive boss","captionOriginal":"","width":{"Desktop":{"point":"40","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-10"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"imageLoad":"eager","fetchPriorityHigh":true,"className":"wp-block-gutenverse-image guten-element guten-image guten-U0mp05"} /-->

<!-- wp:gutenverse/image {"elementId":"guten-RYm2RI","imgSrc":{"media":{"imageId":816,"sizes":{"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/woman-in-red.webp","height":80,"width":80,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"woman in red","captionOriginal":"","width":{"Desktop":{"point":"40","unit":"px"}},"height":{"Desktop":{"unit":"px","point":"40"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-10"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"imageLoad":"eager","fetchPriorityHigh":true,"className":"wp-block-gutenverse-image guten-element guten-image guten-RYm2RI"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":69,"Mobile":50},"sectionVerticalAlign":"center","elementId":"guten-TKr5Nu","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"0"}}}} -->
<!-- wp:gutenverse/star-rating {"elementId":"guten-WkuAUj","title":"","align":{"Desktop":"flex-start"},"starIcon":"fill","rating":5,"total":5,"gap":{"Desktop":"0"},"iconSize":{"Desktop":"14","Mobile":"12"},"iconGap":{"Desktop":"5","Mobile":"4"},"iconColorMarked":{"type":"variable","id":"sixth"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"2"}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-Ws0hjn","titleTag":"span","text":"Over ","focusText":"2k+ reviews","subText":"","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"white"},"mainTypography":{"type":"variable","id":"gv-font-text-small","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"focusColor":{"type":"variable","id":"white"},"focusTypography":{"type":"variable","id":"gv-font-text-small-alt","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"700"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/button {"elementId":"guten-3zn5QG","content":"Get Started ","url":"#","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Tablet":[],"Mobile":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"none","width":"","color":{"r":255,"g":255,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"gtn gtn-long-arrow-alt-right-solid","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yMS4xODggOS4yODFsLTEuNDA2IDEuNDM4IDQuMjgxIDQuMjgxaC0yMC4wNjN2MmgyMC4wNjNsLTQuMjgxIDQuMjgxIDEuNDA2IDEuNDM4IDYuNzE5LTYuNzE5eiI+PC9wYXRoPgo8L3N2Zz4K","iconPosition":"after","iconSpacing":{"Desktop":"25"},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"background":{"type":"default"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none"}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"none"},"right":{"type":"none"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"600"},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-button-primary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"positioningType":{"Desktop":"inline"},"ariaLabel":"get started"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section --><!-- wp:gutenverse/section {"gap":"no","elementId":"guten-nsA4Ao","margin":{"Desktop":[],"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"50","top":"","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-Aq3fUU","margin":{"Desktop":{"unit":"px","dimension":{"top":"-340","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"0","right":"20","left":"20","top":"-320"}},"Mobile":{"unit":"px","dimension":{"top":"-200"}}},"padding":{"Desktop":[],"Tablet":[]},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-zK29Bg","background":{"type":"default","image":{"Desktop":{"id":1138,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/african-asian-blonde-brainstorm-business-businessman-1629588-pxhere.com_.webp"}},"position":{"Desktop":"top center","Mobile":"custom"},"repeat":{"Desktop":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover"},"yposition":{"Mobile":{"point":"1","unit":"px"}},"xposition":{"Mobile":{"point":"-400","unit":"px"}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[]}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"","left":"","top":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"400","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"350","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"350","right":"0","bottom":"0","left":"0"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":34,"Tablet":50,"Mobile":null},"elementId":"guten-eCzciN","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1},"position":{"Desktop":"bottom left"}},"verticalAlign":{"Desktop":"flex-end"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-1","left":"-1"}},"Mobile":{"unit":"px","dimension":{"right":"30","top":"0","bottom":"","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"0","left":"0"}},"Tablet":[]},"hideMobile":false} -->
<!-- wp:gutenverse/icon {"elementId":"guten-f6bjsg","icon":"gtn gtn-play-button","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yLjI4NiAwbDI3LjQyOSAxNi0yNy40MjkgMTZ6Ij48L3BhdGg+Cjwvc3ZnPgo=","iconAlign":{"Desktop":null},"ariaLabel":"play button","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"13","unit":"px"},"Mobile":{"point":"","unit":"px"}},"iconPadding":{"Desktop":"0","Mobile":""},"iconColorTwo":{"type":"variable","id":"white"},"iconShape":"circle","url":"#","animation":{"type":{"Desktop":"none"},"duration":"normal","delay":0},"background":{"type":"default","color":{"type":"variable","id":"gv-color-accent"},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"20"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"14","bottom":"14","right":"18","left":"22"}},"Mobile":{"unit":"px","dimension":{"top":"12","right":"16","bottom":"12","left":"20"}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-3MiyxD","content":"Watch Introduction","type":3,"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-meta-alt","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10"}},"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":0},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-ZtRKcD","textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Noto Sans","value":"Noto Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"15","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"800"},"hideMobile":true} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":66,"Tablet":50,"Mobile":null},"elementId":"guten-vQ0ocU","hideMobile":true} /-->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
